name: dphi160
file:
  losses: runs/dphi160/dphi160_losses.csv
  params: runs/dphi160/dphi160_params.pth
  init_params: runs/dphi160/dphi160_init_params.pth
  plots: runs/dphi160/dphi160_plots.png
dPhi: 1.6
lower_bounds:
- 0.0
- 0.1
- -1.0
upper_bounds:
- 1.6
- 0.99
- 1.0
dataset_size_exponent: 16
train_size: 65536
val_size: 5000
batch_size: 2048
monitor_step: 2000
delete: true
num_steps: 5
num_iters_per_step: 200000
base_lr: 0.003
gamma: 0.24
val_cost_drop_threshold: 0.005
